version: '3'
services:
  go-backend:
    build: ./
    restart: always
    depends_on:
      - db
      - rmq
    environment:
      DRIVER_TYPE: postgres
      APP_PORT: 8080
      DATABASE_CONNECTION_STRING: postgresql://postgres:example@db:5432?sslmode=disable
      RABBITMQ_CONNECTION_STRING: "amqp://guest:guest@rmq:5672/"
    ports:
      - 8080:8080
  rmq:
    image: rabbitmq:3.10.7-management-alpine
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
  db:
    image: postgres:14.5-alpine
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: example
